services:
  - name: instagram-repost-bot
    env: python
    startCommand: "python bot/scheduler.py"
    envVars:
      - key: INSTAGRAM_USERNAME
        sync: false
      - key: INSTAGRAM_PASSWORD
        sync: false

  - name: telegram-webhook
    env: python
    startCommand: "python bot/telegram_bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: WEBHOOK_URL
        value: "https://telegram-webhook.onrender.com"
    ports:
      - 5000
